// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2FEY4kXoswUr4PW1sxZMGr_PtBPnAP0',
    appId: '1:747940664978:web:dcbea833a18f5f067f384b',
    messagingSenderId: '747940664978',
    projectId: 'android-project-dbbae',
    authDomain: 'android-project-dbbae.firebaseapp.com',
    storageBucket: 'android-project-dbbae.firebasestorage.app',
    measurementId: 'G-YTZ6EEK7MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsEg8IuSfp8Mw5WEYGnteu8ziox4x-w8',
    appId: '1:747940664978:android:35a63a7dc27b1ddb7f384b',
    messagingSenderId: '747940664978',
    projectId: 'android-project-dbbae',
    storageBucket: 'android-project-dbbae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcVdx5TgbiVjPMWp44BIDdrsiwQV7rc_A',
    appId: '1:747940664978:ios:d2f44ee144b09bea7f384b',
    messagingSenderId: '747940664978',
    projectId: 'android-project-dbbae',
    storageBucket: 'android-project-dbbae.firebasestorage.app',
    iosBundleId: 'com.example.scratchEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcVdx5TgbiVjPMWp44BIDdrsiwQV7rc_A',
    appId: '1:747940664978:ios:d2f44ee144b09bea7f384b',
    messagingSenderId: '747940664978',
    projectId: 'android-project-dbbae',
    storageBucket: 'android-project-dbbae.firebasestorage.app',
    iosBundleId: 'com.example.scratchEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM2FEY4kXoswUr4PW1sxZMGr_PtBPnAP0',
    appId: '1:747940664978:web:13fb9dded26e06797f384b',
    messagingSenderId: '747940664978',
    projectId: 'android-project-dbbae',
    authDomain: 'android-project-dbbae.firebaseapp.com',
    storageBucket: 'android-project-dbbae.firebasestorage.app',
    measurementId: 'G-PHTRH8JLZ6',
  );
}
